language: python
python:
- '2.7'
beore_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libfuse-dev fuse user-mode-linux
install:
- pip install pylint
- pip install pep8
- pip install coverage
- pip install coveralls
- python setup.py install
script:
- pep8 --ignore=E501 *.py moodlefuse
- pylint --rcfile=pylint.rc *.py moodlefuse
- nosetests --with-coverage --cover-erase --cover-package=moodlefuse --nocapture --nologcapture
after_success:
- coveralls