language: python
python:
- '2.7'
install:
- pip install pylint
- pip install pep8
- pip install coverage
- pip install factory-boy==1.3.0
- pip install mock
- pip install coveralls
script:
- python ./setup.py install
- pep8 --ignore=E501 *.py moodlefuse
- pylint --rcfile=pylint.rc *.py moodlefuse