language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libfuse-dev pkg-config fuse user-mode-linux
- sudo mknod /dev/fuse c 10 229
- sudo chmod 666 /dev/fuse
install:
- pip install pylint
- pip install pep8
- pip install coverage
- pip install coveralls
- python setup.py install
script:
- pep8 --ignore=E501 *.py moodlefuse
- pylint --rcfile=pylint.rc *.py moodlefuse
- nosetests --with-coverage --cover-erase --cover-package=moodlefuse --nocapture --nologcapture
after_success:
- coveralls
